### ISSUE TITLE
integration with gnome 3.12

### ISSUE THREAD

**Issue by DolphinStKom** [multani/sonata#65]
I have been noticing a bug with display and volume control in Sonata after upgrade to Gnome 3.12. I'm not sure, maybe it was provoked by the other updates when gnome was updated.

![2014-07-29](https://cloud.githubusercontent.com/assets/4992884/3734369/31d79986-1716-11e4-9ac0-06d92881f346.jpg)

**Comment by multani** [comment]
It works fine here (I'm using Gnome 3.16.2). Maybe it's a problem with your Gtk theme?

![screenshot from 2015-06-18 23 26 06](https://cloud.githubusercontent.com/assets/65311/8242708/8f92670e-1611-11e5-83ba-b066996112e4.png)

**Comment by DolphinStKom** [comment]
I don't think so... but now it is displayed correctly on GNOME 3.16
You can close this issue
