### ISSUE TITLE
Sonata downloads the lyrics event when they're present in the song's tags

### ISSUE THREAD

**Issue by brunal** [multani/sonata#71]
All my music has the lyrics in its tags. Sonata still downloads it and stores in in `~/.lyrics`. There does not seem to be a way to circumvent that behaviour.

**Comment by multani** [comment]
Lyrics are downloaded by plugins which can be deactivated in the preferences. That would solve your storing problem.

If you want Sonata to also fetch lyrics in your tags, that could be done by another plugin actually ... if only Sonata provided a way to access the current song information. Currently, [the "get lyrics" plugin API only has access to the artist and the title](https://github.com/multani/sonata/blob/master/sonata/info.py#L521), which *should be enough for anybody ©*. Sigh.

Anyway, considering there's, to my knowledge, [only one plugin written against this API](https://github.com/multani/sonata/blob/master/sonata/plugins/lyricwiki.py]), it can probably be changed to access, let's say, the current song information (those given by MPD `current` function). Your lyrics should be inside, and the already existing plugin for Lyrics Wiki could still be updated to work as before.

I'm happily considering patches ;)

**Comment by brunal** [comment]
I've looked a bit more into it and the current problem is that mpd does *not* send that information on a `currentsong`  or `readcomments` command:
* it is not stored by mpd
* were it stored that it would not be sent as multi-line tag values are skipped...

Bugs have been opened on the topic on mpd's bugtracker: bugs.musicpd.org/view.php?id=4280 & bugs.musicpd.org/view.php?id=4281
If it gets fixed/changed then I'll look again in making Sonata use it.

**Comment by multani** [comment]
Oh OK, I saw that MPD was sending some "extra" tags that I had on my songs, but I didn't check for a tag which contained lyrics (I don't think I have any songs with lyrics inside actually).

Anyway, thanks for taking care of this!
