### ISSUE TITLE
Cover not updated on song change in full screen mode

### ISSUE THREAD

**Issue by gtataranni** [multani/sonata#73]
Hello, I'm using sonata 1.7a2-62-gace5e on linux mint, and want to report a little bug.
When in fullscreen mode, on song change the album cover is always substituted by the default cd image.

**Comment by multani** [comment]
Hi,

Thanks for the report! I'll have a look at the problem next week!

**Comment by multani** [comment]
Hi,

sorry for the late reply, but I'm quite busy these days...

On Wed, Feb 18, 2015 at 07:24:40AM -0800, giovanni-t wrote:
> Hello, I'm using sonata 1.7a2-62-gace5e on linux mint, and want to report a little bug.
> When in fullscreen mode, on song change the album cover is always substituted by the default cd image.

I had a quick look already and I confirm something weird's happening
with the fullscreen mode. I couldn't reproduce the specific bug you
mentionned, but on my tests, when a song changed, the cover or the text
wasn't changing at all.

Did you have your problem on songs with different covers or was it the
same album between the different songs?

**Comment by giovanni-t** [comment]
Hi,

It happens in both cases

Giovanni Tataranni
Il 18/mar/2015 22:43 "Jonathan Ballet" <notifications@github.com> ha
scritto:
