### ISSUE TITLE
covers in png files saved as jpg's

### ISSUE THREAD

**Issue by rocus** [multani/sonata#81]
When last.fm delivers a png file as an image for a cover of an album it is shown correctly (I think) but it is saved as a jpg. Subsequently this cover is not a legitimate cover image and will not be shown by sonata.

I found this out by looking in the cover directory and noticed that some pictures were not loadable by a viewer. Changing the extension from jpg to png made the image viewable by that viewer. From this I deduced what seems to be wrong (the first sentence beginning with "When last..... ".

**Comment by multani** [comment]
Right, so I had a look in my collection, and it seems I've got a lot of ``.jpg`` file which are actually PNG files.

A problem I can see is that Sonata already tries *very hard* to find a cover for a song, by looking at several "well-known" locations for a specific ``cover.jpg`` (or another file, there are already 7 possible locations), and adding other locations which are checking for the equivalent file but ending ``.png`` is going to add even more complexity here and lower performances, so I'm not so keen to add new ones.

Another possibility would be to convert the album into a JPEG data, but that means Sonata would possibly lower the quality of the image and I can already see it's not going to please everyone.

I'm open to suggestions and possible fixes, if any, though.

**Comment by multani** [comment]
For those interested, the artwork locator object is here : https://github.com/multani/sonata/blob/master/sonata/artwork.py#L38

**Comment by rocus** [comment]
Jonathan, are you talking about the lastfm plugin or your artwork.py program. If I use the lastfm plugin I only find one image and that image maybe a jpg or png. The origional rhapsody program was indeed able to show you six images. It choose the first by default. I changed that a bit (it looked in google:images) and that worked quite well except for the ocasional weird image.

Because it is now a plugin (origionally  it was part of the sonata python directory) It is now a bit different and I could not immediately find the six image places (in the software).

For me this is less important that the other things I am working on...
